version: '3.8'
volumes:
  mongo-db:

services:
  ecommerce:
    container_name: ecommerce-app
    build:       
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_DB_URI: ${MONGO_DB_URI}
    env_file:
      - .env
    volumes:
      - ./app:/src/ecommerce
      - /src/ecommerce/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo-db:/data/db'
